"""Event names used by the append-only journal."""

from enum import StrEnum


class EventType(StrEnum):
    RUN_CREATED = "RUN_CREATED"
    TRANSITION = "TRANSITION"
    PHASE_STARTED = "PHASE_STARTED"
    PHASE_COMPLETED = "PHASE_COMPLETED"
    PHASE_REUSED = "PHASE_REUSED"
    FAILURE = "FAILURE"
    RETRY_SCHEDULED = "RETRY_SCHEDULED"
    LOCK_ACQUIRED = "LOCK_ACQUIRED"
    LOCK_RELEASED = "LOCK_RELEASED"
    CANCEL_REQUESTED = "CANCEL_REQUESTED"
    HUMAN_APPROVED = "HUMAN_APPROVED"
    ARCHIVED = "ARCHIVED"
    LEGACY_MIGRATED = "LEGACY_MIGRATED"
