"""Stable workflow-state vocabulary."""

from enum import StrEnum


class WorkflowState(StrEnum):
    """A durable state name for a future Dev Autopilot run."""

    CREATED = "CREATED"
    PLAN_VALIDATION = "PLAN_VALIDATION"
    BASELINE_VALIDATION = "BASELINE_VALIDATION"
    IMPLEMENTATION = "IMPLEMENTATION"
    SCOPE_VALIDATION = "SCOPE_VALIDATION"
    FAST_TESTS = "FAST_TESTS"
    AGY_AUDIT = "AGY_AUDIT"
    CLAUDE_REVIEW = "CLAUDE_REVIEW"
    CORRECTION = "CORRECTION"
    FINAL_TESTS = "FINAL_TESTS"
    READY_FOR_HUMAN_REVIEW = "READY_FOR_HUMAN_REVIEW"
    PAUSED_QUOTA = "PAUSED_QUOTA"
    PAUSED_HUMAN_DECISION = "PAUSED_HUMAN_DECISION"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"
